[package]
name = "model"
version = "0.1.0"
authors = ["Fraser King <frasertheking@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.31"
csv = "1.1"
